name = "Gamerpack"
author = "The Gamers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0f14c0a063237978c603bbc1213ffa7167824bcbb727ccfbf48e731a2fb8e48"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
